import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# config server 

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "sample@example.com"
SENDER_PASSWORD = "yourpassword " # Note: not your regular password

def generate_receipt_html(receipt_data, receipt_id):

    """
    Create HTML design for the receipt notification email.
    include tables and action buttons.
    """

    # API links for actions
    # Note: in real deployment, use actual domain instead of localhost
    approve_link = f"http://localhost:8000/api/approve/{receipt_id}"
    reject_link = f"http://localhost:8000/reject_form/{receipt_id}" # leads to a form

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
            <div style="background-color: #4CAF50; padding: 20px; text-align: center; color: white;">
                <h2>New Receipt Received</h2>
                <p>Your review is required</p>
            </div>

            <div style="padding: 20px;">
                <p>Hello,</p>
                <p>The system has processed a new receipt. Please review the details below:</p>
                
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                    <tr style="background-color: #f2f2f2;">
                        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Provider:</strong></td>
                        <td style="padding: 10px; border: 1px solid #ddd;">{receipt_data.get('provider', 'N/A')}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Receipt No:</strong></td>
                        <td style="padding: 10px; border: 1px solid #ddd;">{receipt_data.get('receipt_no', 'N/A')}</td>
                    </tr>
                    <tr style="background-color: #f2f2f2;">
                        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Date:</strong></td>
                        <td style="padding: 10px; border: 1px solid #ddd;">{receipt_data.get('date', 'N/A')}</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border: 1px solid #ddd;"><strong>Total:</strong></td>
                        <td style="padding: 10px; border: 1px solid #ddd; font-size: 1.2em; color: #2c3e50;">
                            <strong>${receipt_data.get('total_amount', '0.00')}</strong>
                        </td>
                    </tr>
                </table>

                <div style="text-align: center; margin-top: 30px;">
                    <a href="{approve_link}" style="background-color: #28a745; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; margin-right: 10px; font-weight: bold;">
                        ✓ Approve
                    </a>
                    <a href="{reject_link}" style="background-color: #dc3545; color: white; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold;">
                        ✕ Reject
                    </a>
                </div>
                
                <p style="font-size: 12px; color: #777; margin-top: 30px; text-align: center;">
                    Reference ID: {receipt_id} | Automatically generated by AI System
                </p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_notification(destiny, receipt_data, receipt_id):
    """Send email notification about new receipt."""

    # create message
    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = destiny
    msg['Subject'] = f"Required action: Receipt {receipt_data.get('receipt_no', '---')}"

    # generate HTML content
    html_body = generate_receipt_html(receipt_data, receipt_id)
    msg.attach(MIMEText(html_body, 'html'))

    try: 

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        print(f" Mail sent successfully to {destiny} regarding Receipt ID: {receipt_id}")
        return True
    except Exception as e:
        print(f" Failed to send email to {destiny}: {e}")
        return False
    
# test block

if __name__ == "__main__":

    # mock data
    sample_receipt = {
        "provider": "ACME Supplies S.A.",
        "receipt_no": "F123-456",
        "date": "15/09/2023",
        "total_amount": "1,250.75"
    }

    send_notification("sample@example.com", sample_receipt, 1)